config/routes.rb
Rails.application.routes.draw do
  
  root               'static_pages#home'

  get 'about'     => 'static_pages#about'

  get 'contacts'  => 'static_pages#contacts'

  get 'service'   => 'static_pages#service'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contacts
  end

  def service  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#Returns the full title on a page per basis
	def full_title(page_title = '')
	  base_title = "Maitco Website"
	  if page_title.empty?
	  	base_title
	  else
	  	page_title + " | " + base_title
	  end
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  copyright © 2015 | Maitco company. All Rights Reserved
  </small>
  <nav>
    <ul>
      <li><%= link_to "Developer", '#' %></li>
      <li><a href="http://maitco.blogspot.com/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-custom">
	  	<div class="container">
	  	  <%= link_to "MaitCO", root_path, id: "logo" %>
	  	  <nav>
	  	    <ul class="nav navbar-nav navbar-right">
	  	      <li><%= link_to "Home", 		root_path %></li>
	  	      <li><%= link_to "Services",   service_path %></li>
	  	      <li><%= link_to "Contacts", 	contacts_path %></li>
	  	      <li><%= link_to "About", 		about_path %></li>
	  	    </ul>
	  	  </nav>
	   	</div>
	  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  	  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  <%= render 'layouts/header' %>
	  <div class="container">
	  	<%= yield %>
	  	<%= render 'layouts/footer' %>
	  </div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="jumbotron">
  <div class="thumbnail">
  	<%= image_tag("about-us.jpg", :alt => "about-us image") %>
  </div>
</div>
<div class="container">
	Maitco is the company that provide IT services to local or company or any organisation<br/> We are located at Ubungo, Dar es salaam opposite to Oilcom petrol station
</div>

app/views/static_pages/contacts.html.erb
<% provide(:title, "Contacts") %>
<div class="center jumbotron">
   <div class="thumbnail">
     <%= image_tag("contacts.jpg", :alt => "contacts images") %>
   </div>
</div>
<div class="container">
	<h3>Contact us through</h3>
	<ul>
		<li>Call/SMS/Whatsapp: <em>0789291159</em></li>
		<li>Email: <em>malaikakimomwe@gmail.com</em></li>
		<li>Facebook: <em><a href="facebook.com/maitco">Like us</a></em></li>
	</ul>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">

<!--Slider goes here                       -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <%= image_tag("it-services-list.png", :alt => "It it-services-list") %>
        <div class="carousel-caption">
          <p>Services provided</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag("contacts.jpg", :alt => "contacts") %>
        <div class="carousel-caption">
          <p>Contacts us.</p>
        </div>
      </div>
    
      <div class="item">
        <%= image_tag("about-us.jpg", :alt => "About us image") %>
        <div class="carousel-caption">
          <p>About us.</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div class="row">
	<div class="col">
		Maitco company provide IT services for individual and companies. We also provide consultation about IT in general. 
	</div>
	<div class="col-sm-4">
		<h2>Mission</h2>
		<p>Our mission is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj</p>
		<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#mission"><i>read more...</i></button>
		  <div id="mission" class="collapse">
		  	Our  mission is bla b;la hbla b;la bajhakajjhyja khakha hjhasjnkasua kashkhakkha
		  </div>
	</div>
	<div class="col-sm-4">
		<h2>Vission</h2>
		<p>Our vission is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj</p>
		<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#vission"><i>read more...</i></button>
		  <div id="vission" class="collapse">
		  	Our  vission is bla b;la hbla b;la bajhakajjhyja khakha hjhasjnkasua kashkhakkha
		  </div>
	</div>
	<div class="col-sm-4">
		<h2>Objectives</h2>
		<p>Our objective is blah blah blha abjkakjakhak ajjkhahkjha ajajkajhkah ajhkahkakhakha ajjaj</p>
		<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#objective"><i>read more...</i></button>
		  <div id="objective" class="collapse">
		  	Our  mission is bla b;la hbla b;la bajhakajjhyja khakha hjhasjnkasua kashkhakkha
		  </div>
	</div>

</div>

app/views/static_pages/service.html.erb
<%= provide(:title, "Services") %>
<div class="center jumbotron">
   <%= image_tag("it-services-list.png", :alt => "it-service-list") %>
</div>
<div id="container">
  <h3>We provide the following services</h3>
    <ul>
    	<li>Website development</li>
    	<li>Software development</li>
    	<li>Pc mantainance</li>
    	<li>Blog design and development</li>
    </ul>
</div>